# Generated by Django 5.0.4 on 2024-04-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_numberrange_territory_gar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberrange',
            name='region',
            field=models.CharField(),
        ),
    ]
